# Site settings
title: PatternFly | open interface project
email: patternfly@redhat.com
description: PatternFly is an open source web user interface framework promoting consistency and usability across IT applications through UX patterns and widgets
baseurl: '/patternfly-org/' # the subpath of your site, e.g. /blog/
url: 'https://priley86.github.io/patternfly-org/' # the base hostname & protocol for your site
collections:
- whats-news
blogurl: https://blog.patternfly.org
exclude: ["components/patternfly/tests-src"]
navbar-pf-navbar-brand-icon: true
navbar-pf-alt-navbar-brand-icon: true
navbar-logo-icon: '/assets/img/logo.svg'
navbar-logo-alt-icon: '/assets/img/logo-alt.svg'
navbar-brand-icon: '/assets/img/brand.svg'
navbar-brand-alt-icon: '/assets/img/brand-alt.svg'
title-product: 'PatternFly Enterprise Application'
